// A frozen, verbatim copy of `resolveAssistantScope` as it was before REG-2b
// (develop 8283638, platform/business_tools.dart). The differential test in
// scope_resolver_differential_test.dart compares the host's single-entry
// `ScopeResolver` against it. Do not edit this file to follow the new code: if
// the two ever differ, that is the thing the test exists to show.
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:muyon/app/bootstrap.dart';
import 'package:muyon/platform/business_tools.dart' show objectIdentity;
import 'package:prototype_module/prototype_module.dart';
import 'package:muyon_module_api/muyon_module_api.dart';
import 'package:supplier_core/supplier_core.dart';

/// Domain objects remain in their module. The host only resolves identities
/// and versions; global scope does not copy their content into model prompts.
Future<ResolvedAssistantScope> legacyResolveAssistantScope(
  MuyonHost host,
  AssistantScope scope,
) async {
  await host.activateInquiry();
  await host.activateResearch();
  final objects = <String, ObjectRef>{};
  void add(ObjectRef ref) => objects[objectIdentity(ref)] = ref;
  final inquiry = host.inquiry?.runtime.state.store;
  if (inquiry != null) {
    for (final type in entityTypes) {
      for (final row in inquiry.db.select(
        'SELECT * FROM $type WHERE deleted=0',
      )) {
        final data = jsonDecode(row['data'] as String) as Map;
        add(
          ObjectRef(
            moduleId: 'inquiry',
            objectType: type,
            objectId: row['id'] as String,
            nativeProjectId: type == 'project'
                ? row['id'] as String
                : data['project_id'] as String?,
            revisionRef: row['version'].toString(),
            contentDigest: sha256
                .convert(utf8.encode(row['data'] as String))
                .toString(),
          ),
        );
      }
    }
  }
  final research = host.research?.store;
  if (research != null) {
    for (final project in research.projects()) {
      add(
        ObjectRef(
          moduleId: 'research',
          objectType: 'project',
          objectId: project.id,
          nativeProjectId: project.id,
          contentDigest: sha256
              .convert(
                utf8.encode(
                  jsonEncode([
                    project.title,
                    project.question,
                    project.nextStep,
                  ]),
                ),
              )
              .toString(),
        ),
      );
      for (final document in research.documents(project.id)) {
        final file = File(document.absolutePath);
        final digest = file.existsSync()
            ? (await sha256.bind(file.openRead()).first).toString()
            : 'missing';
        add(
          ObjectRef(
            moduleId: 'research',
            objectType: 'document',
            objectId: document.id,
            nativeProjectId: project.id,
            contentDigest: digest,
          ),
        );
      }
      for (final entry in research.entries(project.id)) {
        add(
          ObjectRef(
            moduleId: 'research',
            objectType: 'entry',
            objectId: entry.id,
            nativeProjectId: project.id,
            contentDigest: sha256
                .convert(utf8.encode(jsonEncode(entry.data)))
                .toString(),
          ),
        );
      }
    }
  }
  await host.activatePrototype();
  final prototype = host.prototype?.store;
  if (prototype != null) prototypeScopeRefs(prototype).forEach(add);
  for (final document in host.services.knowledge.documents()) {
    if (await host.services.knowledge.isCurrent(document.id)) {
      final ref = document.source;
      objects.putIfAbsent(objectIdentity(ref), () => ref);
    }
  }
  if (scope.kind == AssistantScopeKind.global) {
    return ResolvedAssistantScope(
      requested: scope,
      objects: objects.values.toList(),
    );
  }
  final workspace = scope.workspaceId;
  if (workspace != null &&
      !host.workspaces.all().any((w) => w.id == workspace)) {
    throw StateError('Unknown workspace');
  }
  bool inWorkspace(ObjectRef ref) {
    if (workspace == null) return true;
    final binding = host.workspaces.binding(workspace, ref.moduleId);
    return binding != null && binding.nativeProjectId == ref.nativeProjectId;
  }

  if (scope.kind == AssistantScopeKind.workspace) {
    return ResolvedAssistantScope(
      requested: scope,
      objects: objects.values.where(inWorkspace).toList(),
    );
  }
  final selected = <ObjectRef>[];
  for (final requested in scope.objects) {
    final current = objects[objectIdentity(requested)];
    if (current == null ||
        !inWorkspace(current) ||
        (requested.revisionRef != null &&
            requested.revisionRef != current.revisionRef) ||
        (requested.contentDigest != null &&
            requested.contentDigest != current.contentDigest)) {
      throw StateError(
        'Selected object is missing, changed or outside workspace',
      );
    }
    selected.add(current);
  }
  return ResolvedAssistantScope(requested: scope, objects: selected);
}

// Frozen original prototype candidate/digest algorithm, formerly host-owned.
List<ObjectRef> prototypeScopeRefs(PrototypeStore store) => [
  for (final page in store.pages()) ...[
    ObjectRef(
      moduleId: prototypeModuleId,
      objectType: 'page',
      objectId: page.id,
      nativeProjectId: page.id,
    ),
    for (final v in store.versions(page.id))
      ObjectRef(
        moduleId: prototypeModuleId,
        objectType: 'version',
        objectId: v.id,
        nativeProjectId: page.id,
        contentDigest: v.digest,
      ),
    for (final f in store.feedback(page.id))
      ObjectRef(
        moduleId: prototypeModuleId,
        objectType: 'feedback',
        objectId: f.id,
        nativeProjectId: page.id,
        contentDigest: sha256.convert(utf8.encode(f.text)).toString(),
      ),
  ],
];
